name: Check Month

on:
  push:
    branches:
      - main

jobs:
  check_month:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check if month is odd
      id: check_month
      run: echo "::set-output name=is_odd::$(($(date +'%-m') % 2))"
      
    - name: Print current month
      run: echo "Current month is $(date +'%B')"
      
    - name: Fail if month is odd
      if: ${{ steps.check_month.outputs.is_odd == '1' }}
      run: exit 1  # Fail the workflow if month is odd
