name: Example Failing Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Run failing command
        run: |
          echo "This is a failing command"
          exit 1  # Simulate a failure
